### ISSUE TITLE
Widget does not work on iOS

### ISSUE THREAD

**Issue by thendricks86** [AuraQ/AutoCompleteForMendix#18] opened 2016-12-02 06:16 UTC
During testing for implementing this widget into our project we realized that the widget will not work on iPhone. Responsive and Android both work as expected, but on iOS the widget will not respond when tabbed on, preventing the search bar to fold open to enable text input. Test was executed using the Mendix Developer App. Please advise if this will be addressed in the near future. Thank you.

**Comment by hganzeboom** [comment] 2016-12-08 10:28
Same issue here. Could you please tell us if this will be fixed in the near future? Thanks in advance.

**Comment by lindski** [comment] 2016-12-09 12:40
Thanks... will investigate this (probably over Christmas) and see what I can do to fix it.

Out of interest, is this using the widget via the browser, or via a hybrid mobile app?

**Comment by hganzeboom** [comment] 2016-12-09 13:52
Hi Lindski,

Thank you for your response.
We are using this widget via a hybrid mobile app.

It would also be nice if the "No results microflow" could automatically be triggered, instead of clicking on the "no results found text", just like creating labels in Mendix App Platform (sprintr) :-)

Kind regards,

H. Ganzeboom

**Comment by lindski** [comment] 2016-12-09 16:02
Do you have a sample application I could use to debug the issue? Haven't done much with hybrid apps.

Think an auto trigger could get a bit annoying, as people will occasionally mistype search terms.

**Comment by hganzeboom** [comment] 2016-12-12 07:53
You are probably right about the no results microflow.

Next Thursday I will try to give you a sample application.

**Comment by thendricks86** [comment] 2017-01-04 03:40
You can put the widget in any mobile form and try to open the app on an iPhone using the Mendix developer app. I can provide you with a sample application if you haven't received one yet :)

**Comment by lindski** [comment] 2017-01-04 09:19
A sample app would be appreciated! I tried to put one together over Christmas so I could debug it through an emulator but don't have an Apple developer account so couldn't actually get the phonegap app built.

**Comment by rcha103** [comment] 2017-01-09 08:04
Hi, our team encountered the same issue too while testing the app via hybrid mobile app. I have created a sample app for you to use and test via hybrid mobile app as well. 

https://drive.google.com/open?id=0B1X1uTkYEJDmNzg5WjFZVk53eXc

**Comment by lindski** [comment] 2017-01-12 09:50
Thanks for the sample, I've been able to reproduce this both via a hybrid app and also using Chrome's device toolbar.

Even the most basic select2 initialisation is an issue when run in a widget, however if I run the same code outside of Mendix, everything works as expected.

This is going to require further investigation so unlikely to be a quick fix I'm afraid

**Comment by lindski** [comment] 2017-02-24 15:29
Thanks to @Da-Dude, I think we finally have a fix for this.

Latest version available from the test project

**Comment by hganzeboom** [comment] 2017-03-01 08:24
It is fixed, thank you very much!

**Comment by hganzeboom** [comment] 2017-03-13 11:01
It looks like after the widget is used in the application, every Microflow is getting triggered twice. You can test it by creating a Microflow button and debug it after the autocomplete widget is used. In my example, I use the Search - XPath. This occurs on iOs.

On desktop however, when the row on which the AutoCompleteWidget is used has conditional visability, in the on change microflow that is used, a pop-up message is shown twice.

**Comment by Da-Dude** [comment] 2017-03-14 11:24
Just added a fix for the double-trigger behaviour. 
Seems to be working as intended now. 

Could you let us know if you're still having this issue?

**Comment by hganzeboom** [comment] 2017-03-14 13:03
It seems to be working now.. thank you very much! 👍

**Comment by lindski** [comment] 2017-03-20 14:27
V3 now available from the appstore

[https://appstore.home.mendix.com/link/app/2695/AuraQ-Limited/AutoComplete-widget](https://appstore.home.mendix.com/link/app/2695/AuraQ-Limited/AutoComplete-widget)

**Closed** 2017-03-31 18:20 UTC
